apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jenkins-admin@percona.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          route53:
            region: eu-central-1
            hostedZoneID: Z1H0AFAU7N8IMC
        selector:
          dnsZones:
            - "cd.percona.com"
