apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jenkins-eks-poc
  region: eu-central-1
  version: "1.31"
  tags:
    iit-billing-tag: jenkins-eks-poc
    environment: ci
    managed-by: eksctl

vpc:
  nat:
    gateway: Single

iam:
  withOIDC: true

managedNodeGroups:
  - name: jenkins-ng
    instanceType: t3.xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 50
    volumeType: gp3
    availabilityZones:
      - eu-central-1b
    privateNetworking: true
    tags:
      iit-billing-tag: jenkins-eks-poc
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        ebs: true
        albIngress: true
        certManager: true

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
