apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ps57-3-jenkins-home
  namespace: jenkins
  labels:
    iit-billing-tag: jenkins-eks-poc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
