controller:
  image:
    registry: "<account-id>.dkr.ecr.eu-central-1.amazonaws.com"
    repository: jenkins-percona
    tag: "2.528.3"
    pullPolicy: IfNotPresent
  installPlugins: false
  overwritePluginsFromImage: false
  initializeOnce: true
  javaOpts: >-
    -Xms3072m -Xmx4096m -Xss4m -server
    -Djava.awt.headless=true
    -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=600
  resources:
    requests:
      cpu: "1000m"
      memory: "4Gi"
    limits:
      cpu: "4000m"
      memory: "6Gi"
  serviceType: ClusterIP
  agentListenerPort: 50000
  agentListenerServiceType: LoadBalancer
  agentListenerServiceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "iit-billing-tag=jenkins-eks-poc"
  numExecutors: 1
  executorMode: "EXCLUSIVE"
  ingress:
    enabled: true
    ingressClassName: alb
    hostName: ps57-2.cd.percona.com
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:<account-id>:certificate/1ec6590a-0529-4af0-81e9-ec59ec71aab2"
      alb.ingress.kubernetes.io/healthcheck-path: /login
      alb.ingress.kubernetes.io/tags: "iit-billing-tag=jenkins-eks-poc"
    tls:
      - hosts:
          - ps57-2.cd.percona.com
  JCasC:
    defaultConfig: false
    overwriteConfiguration: false
  podLabels:
    iit-billing-tag: jenkins-eks-poc
  containerEnv:
    - name: JENKINS_URL
      value: "https://ps57-2.cd.percona.com/"
    - name: JENKINS_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ps57-2-admin
          key: password
          optional: true
persistence:
  enabled: true
  existingClaim: ps57-2-jenkins-home
  subPath: "ps57.cd.percona.com"
serviceAccount:
  create: false
  name: jenkins
agent:
  enabled: false
