# Default class — multi-AZ, gp3, Delete on PVC delete.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp3
  encrypted: "true"
  iops: "3000"
  throughput: "125"
allowVolumeExpansion: true
---
# Monitoring class — single-AZ (us-east-1a), Retain. Used by Prometheus / Alertmanager / Grafana.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-monitoring-1a-retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.ebs.csi.aws.com/zone
        values: ["us-east-1a"]
parameters:
  type: gp3
  encrypted: "true"
  iops: "3000"
  throughput: "125"
allowVolumeExpansion: true
---
# Jenkins-master class — single-AZ (us-east-1a), Retain. Used by Jenkins StatefulSets.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-jenkins-1a-retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.ebs.csi.aws.com/zone
        values: ["us-east-1a"]
parameters:
  type: gp3
  encrypted: "true"
  iops: "3000"
  throughput: "125"
allowVolumeExpansion: true
