apiVersion: v2
name: aws-load-balancer-controller
version: 0.1.0
description: Umbrella chart for the AWS Load Balancer Controller addon.
type: application
dependencies:
  - name: aws-load-balancer-controller
    version: 3.2.2
    repository: https://aws.github.io/eks-charts
